# This is the config file for building and testing Geo::GDAL with Travis-ci.org

os:
  - linux

language: perl
perl:
  - "5.10"

before_install:
  - ./ci/prereq.sh

install:
  - cpanm -v --installdeps --notest .

script: "perl Makefile.PL; make; make test"

branches:
  only:
    - master

notifications:
  recipients:
    - ari.jolma@gmail.com
  email:
    on_success: change
    on_failure: always
